### ISSUE TITLE
Avoiding duplicated static items

### ISSUE THREAD

**Issue by kule** [lucasefe/themes_for_rails#22]
Hiya Lucas,

I'd really like to set this up so the images/javascripts/stylesheets directories could be symlinked to the actual themes directory e.g.

Rails.root/public/themes/theme_name -> 
Rails.root/themes/theme_name/public/

Then in the theme folder you have:

```
$app_root
  themes/
    [theme_name]
      public/
         images/
         stylesheets/
         javascripts/
      views/
        layouts/
```

This way you don't need the themes:cache:create/update/delete tasks (but you'd need to setup the rails app/capistrano deploy task accordingly).  It also means you can edit a theme design and have the changes reflect in your app straight away rather than having to run a rake task but still keeps the actual view files secure.

I'm thinking of creating this for myself but is this some you would be interested in having in the main gem?

[EDIT: opps; somehow this got submitted before I had finished]

**Comment by lucasefe** [comment]
As far as I know, in development mode you don't to use the rake tasks. Everything is handled automatically by the gem, so there must be something wrong in your setup. 

Also, creating symlinks is not a good practice, because they are not supported on Windows. 

Tell me more about the problem you are having and don't forget to include information about your app. 

Cheers

**Comment by kule** [comment]
Don't worry you are correct - I must've ran the rake task on development and then it uses the files in the public folder rather than the ones in the themes folder - opps!

Thanks for your time.

**Comment by lucasefe** [comment]
No problem, dude. I am here to help.
