### ISSUE TITLE
Get asset from non-current theme

### ISSUE THREAD

**Issue by holtkampw** [lucasefe/themes_for_rails#23]
I tried this:

```
  <img src="<%= current_theme_image_path('small_logo.png', 'admin') %>"/>
```

As per this in the sample page:

```
 current_theme_image_path('logo.png', 'purple')   # => /themes/purple/images/logo.png
```

I only see this url helper (only takes asset):

```
   def current_theme_image_path(asset)
         image, extension = asset.split(".")
         base_theme_image_path(:theme => self.theme_name, :asset => "#{image}.#{extension}")
   end
```

I was hoping to use this feature.  Is it something that has been removed on purpose? Or perhaps I'm just using it wrong?  
Thanks for the awesome gem!

**Comment by lucasefe** [comment]
You have to use theme_image_path and use it like this:

theme_image_path(:asset => "photo.png", :theme => "purple")

current_theme_image_path doesn't allow the theme to be set because it's always talking about the current theme (the one that is selected at that moment), as the name implies. 

See https://github.com/lucasefe/themes_for_rails/blob/master/lib/themes_for_rails/view_helpers.rb#L20

Cheers

**Comment by holtkampw** [comment]
Hmm that doesn't seem to work.  It renders this:

```
/themes/<CURRENT_THEME>/images/asset=photo.png&theme=<NEW_THEME>
```

I now get the difference between current_theme_\* and theme_\* (makes complete sense), however, those methods are simply aliased so they do exactly the same thing?

Perhaps it should be something like this? https://gist.github.com/833825

**Comment by lucasefe** [comment]
When you are right, you are right :) 

I just fixed it. Do a  bundle update (I assume that you are using the gem right from the master branch, right? ) and tell me what do you think now.

**Comment by holtkampw** [comment]
Awesome!  Works perfect.  Again, amazing gem.

**Comment by lucasefe** [comment]
Thanks, man. Glad to help. Feedback is the part of this project that I enjoy the most.
