### ISSUE TITLE
Available themes + thumbs

### ISSUE THREAD

**Issue by matheusca** [lucasefe/themes_for_rails#6]
Hey, my friend Ramon Soares give a idea about feature. This feature is a helper which return all themes on system and thumbs.

What do you think?
How do organization folder for thumbs?

**Comment by lucasefe** [comment]
Let me see if I understand it right. You want to be able to provide a list of thumbnails, so the "user" can choose from images instead of theme names? 

I think that a thumb.{png|jpeg} at the root of each theme folder will suffice. What  do you think? It's an easy thing to implement, at least at first sight.

**Comment by matheusca** [comment]
Yeah, the helper return the name and url thumb.

I like, just put thumb.{png|jpeg} in folder of theme. Once I will develop the helpers methods and after configuration to choose which images types(not just jpeg or png) want wear.

What do you think?

**Comment by lucasefe** [comment]
The last sentence, when you say "want wear". What do you mean? I speak spanish normally and my english is not perfect. But regarding the first sentence, it looks good to me. Are you willing to take that task? Or do you want to? :)

**Comment by matheusca** [comment]
Sorry my english, sometimes I confused the words hehe. I mean "want use", I dont know why write wear, but ok.

Ok, I will implement. 

Thanks and sorry :D

**Comment by lucasefe** [comment]
Cool, great. Remember to write tests. It's really important! :)
